name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.14.0]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps if requirements.txt exists
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          fi

      - name: Lint or syntax check
        run: |
          set -e
          if command -v ruff >/dev/null 2>&1; then
            ruff .
          elif command -v flake8 >/dev/null 2>&1; then
            flake8 .
          else
            # basic syntax check for all .py files
            find . -name '*.py' -not -path './.git/*' -not -path './venv/*' -print0 | xargs -0 -n1 python -m py_compile
          fi

      - name: Run tests if tests exist
        run: |
          set -e || true
          if [ -d tests ] || ls test_*.py >/dev/null 2>&1; then
            pytest -q || true
          else
            echo "No tests detected; skipping pytest"
          fi
